# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Go Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run Build
        run: go build cmd/main.go

  deploy:
    name: Deploy in AWS EC2
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/walkwalkgo/walkwalkgo-telegram-bot
          git pull
          ls -al
          export TOKEN=${{ secrets.TOKEN }}
          export MONGO_URI=${{ secrets.MONGO_URI }}
          docker build --build-arg TOKEN="$TOKEN" --build-arg MONGO_URI="$MONGO_URI" -t telebot .
          docker image prune -f
          docker run -d --name telebot telebot
          





